CREATE TABLE userprofile (
	id int4 DEFAULT nextval('userprofile_seq_id'::regclass) NOT NULL,
	userid int4 NOT NULL,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	email varchar(255) NULL,
	avatar varchar(255) NULL,
	birth_date date NULL,
	date_created timestamp DEFAULT now() NOT NULL,
	"role" public.userprofile_role DEFAULT 'player_manual'::userprofile_role NULL,
	league int4 NULL,
	provider_email varchar(255) NULL,
	rpe bool DEFAULT false NOT NULL,
	tqr bool DEFAULT false NOT NULL,
	"statistics" bool DEFAULT false NOT NULL,
	smart_assistant bool DEFAULT false NOT NULL,
	coach bool DEFAULT false NOT NULL,
	nutritionist bool DEFAULT false NOT NULL,
	kinesiologist bool DEFAULT false NOT NULL,
	tk_fcm varchar(255) NULL,
	medicalreport varchar(255) NULL,
	blocked_user bool DEFAULT false NULL,
	motive_blocked varchar(255) NULL,
	onboarding bool DEFAULT false NULL,
	current_team varchar(255) NULL,
	id_language int4 NULL,
	current_tournament int4 NULL,
	current_fase int4 NULL,
	date_access date NULL,
	dni varchar NULL,
	is_demo bool NULL,
	migrate bool DEFAULT false NULL,
	start_migration bool DEFAULT false NULL,
	is_premium bool DEFAULT false NULL,
	trial_subs bool NULL,
	expirate_date_sub date NULL,
	email_mastrainer varchar(255) NULL,
	username varchar(50) NULL,
	description varchar NULL,
	gallery varchar NULL,
	tk_fcm_old varchar NULL,
	country int4 NULL,
	localitys int4 NULL,
	province int4 NULL,
	is_reporter bool DEFAULT false NULL,
	avatar_50 varchar(100) NULL,
	avatar_100 varchar(100) NULL,
	gender public.gender_enum NULL,
	avatar_rembg varchar(255) NULL,
	CONSTRAINT pk_userprofile PRIMARY KEY (id)
);